# Generated by Django 4.2.7 on 2023-11-23 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
