# Generated by Django 4.2.7 on 2023-11-15 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_document_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
